name: A Basic workflow
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello,World!"

  build-db:
    needs: [build-app]
    runs-on: windows-latest
    steps:
        - run: echo "Hello windows"
  
  package:
    needs: [build-app,build-db]
    runs-on: self-hosted
<<<<<<< HEAD
      steps:
        - run: echo "Hello macos"

jobs:
  build-api:
    runs-on: windows-latest
      steps:
        - run: echo "Hello World"
=======
    steps:
        - run: echo "Hello macos"
>>>>>>> d7a5f1df760cbed5223e36dd4a45627c0f23b69f
